FROM condaforge/mambaforge:24.9.2-0

ARG CONDA_ENV_NAME='iseq'
ENV CONDA_DIR=/opt/conda
ENV MAMBA_NO_BANNER=1

WORKDIR /work

# Install 'file' as not included in base image but required by iseq
RUN apt-get update && apt-get install -y --no-install-recommends file \
    && rm -rf /var/lib/apt/lists/*

RUN mamba create -y -n "${CONDA_ENV_NAME}" \
    -c bioconda -c conda-forge \
    "iseq==1.9.5" \
    && mamba clean --all --yes

ENV PATH="${CONDA_DIR}/envs/${CONDA_ENV_NAME}/bin:${PATH}"

CMD ["/bin/bash"]
