FROM debian:bookworm-slim

ARG MAMBAFORGE_VERSION=25.3.1-0
ARG CONDA_ENV_NAME='hifiasmmeta'
ENV CONDA_DIR=/opt/conda \
    MAMBA_NO_BANNER=1 \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /work

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates wget git build-essential zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Mambaforge
RUN wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/download/${MAMBAFORGE_VERSION}/Miniforge3-${MAMBAFORGE_VERSION}-Linux-x86_64.sh" \
    && bash Miniforge3.sh -b -p "${CONDA_DIR}" \
    && rm Miniforge3.sh

ENV PATH="${CONDA_DIR}/bin:${PATH}"

# Create the conda environment using Mamba
RUN mamba create -y -n "${CONDA_ENV_NAME}" \
    -c bioconda -c conda-forge \
    "minimap2==2.30" \
    "samtools==1.22.1" \
    && mamba clean --all --yes

# Download and install hifiasm-meta
RUN git clone --depth=1 https://github.com/xfengnefx/hifiasm-meta.git /tmp/hifiasm-meta \
    && cd /tmp/hifiasm-meta \
    && make -j"$(nproc)" \
    && install -m 0755 hifiasm_meta /usr/local/bin/ \
    && rm -rf /tmp/hifiasm-meta

ENV PATH="${CONDA_DIR}/envs/${CONDA_ENV_NAME}/bin:${PATH}"

CMD ["/bin/bash"]
