FROM condaforge/mambaforge:24.9.2-0

ARG CONDA_ENV_NAME='singlem'
ENV CONDA_DIR=/opt/conda \
    MAMBA_NO_BANNER=1 \
    DEBIAN_FRONTEND=noninteractive \
    PATH=$CONDA_DIR/envs/$CONDA_ENV_NAME/bin:$PATH

WORKDIR /work

RUN mamba create -y -n "${CONDA_ENV_NAME}" \
    -c bioconda -c conda-forge \
    "singlem==0.20.3" \
    && mamba clean --all --yes

CMD ["/bin/bash"]
