FROM condaforge/miniforge3:26.3.2-3@sha256:95195a50e20f7929a31a68ea407cefe117423258639efb6b66f0518e4b86f8ee

ARG CONDA_ENV_NAME='unicycler'
ENV CONDA_DIR=/opt/conda \
    MAMBA_NO_BANNER=1 \
    DEBIAN_FRONTEND=noninteractive \
    PATH=$CONDA_DIR/envs/$CONDA_ENV_NAME/bin:$PATH

WORKDIR /work

RUN mamba create -y -n "${CONDA_ENV_NAME}" \
    -c bioconda -c conda-forge \
    "unicycler==0.5.1" \
    "spades==4.3.0" \
    "python=3.10" \
    && mamba clean --all --yes

CMD ["/bin/bash"]
