FROM condaforge/mambaforge:24.9.2-0

ARG CONDA_ENV_NAME='metaspades'
ENV CONDA_DIR=/opt/conda
ENV MAMBA_NO_BANNER=1

WORKDIR /work

# Create the conda environment using Mamba
RUN mamba create -y -n "${CONDA_ENV_NAME}" \
    -c bioconda -c conda-forge \
    "spades==4.2.0" \
    "fastp==1.0.1" \
    && mamba clean --all --yes

ENV PATH="${CONDA_DIR}/envs/${CONDA_ENV_NAME}/bin:${PATH}"

CMD ["/bin/bash"]
