FROM condaforge/mambaforge:24.9.2-0

ARG CONDA_ENV_NAME='iseq'
ENV CONDA_DIR=/opt/conda \
    MAMBA_NO_BANNER=1 \
    DEBIAN_FRONTEND=noninteractive \
    PATH=$CONDA_DIR/envs/$CONDA_ENV_NAME/bin:$PATH

WORKDIR /work

RUN mamba create -y -n "${CONDA_ENV_NAME}" -c conda-forge -c bioconda \
      "iseq==1.9.8" \
      "sra-tools==3.2.1" \
      "aria2==1.37.0" \
      "pigz==2.8" \
      "pbzip2==1.1.13" \
      "curl" \
      "file" \
    && mamba clean --all --yes

CMD ["/bin/bash"]
