FROM condaforge/mambaforge:24.9.2-0

ARG CONDA_ENV_NAME='metaspades'
ENV CONDA_DIR=/opt/conda \
    MAMBA_NO_BANNER=1 \
    DEBIAN_FRONTEND=noninteractive \
    PATH=$CONDA_DIR/envs/$CONDA_ENV_NAME/bin:$PATH

WORKDIR /work

RUN mamba create -y -n "${CONDA_ENV_NAME}" \
    -c bioconda -c conda-forge \
    "spades==3.15.5" \
    "fastp==1.0.1" \
    "bowtie2=2.5.4" \
    "samtools==1.22.1" \
    "python=3.11" \
    && mamba clean --all --yes

CMD ["/bin/bash"]
